spring.application.name=authentication
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication
spring.datasource.username=cruduser
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG
jwt.secret=mi-super-secreto-aleatorio-1234567890
jwt.expiration=3600000
